### ISSUE TITLE
Improve Continuous Integration and Deployment 

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#1641]
In order to improve our Continuous Integration and Continuous Deployment pipelines we need to perform several activities. At the very least we need to pick between Wercker, Travis and ContinuousPHP for a CI provider and then create an automated workflow for deployment of the Website, phpDocumentor 2 and phpDocumentor 3 by fixing the phing build scripts.

At current the working assumption is that Continuous PHP will be our provider as it seems to tick all the boxes.
## Tasks
- [x] Confirm that ContinuousPHP is our new CI platform
- [ ] Investigate and implement how to do a staging environment for the release platform
- [ ] Finish automation of phpDocumentor 2 releases
- [x] Finish automation of phpDocumentor 3 releases
- [ ] Finish automation of the Website
- [ ] Finish automation of the Documentation generation
- [x] Setup ContinuousPHP to perform releases when a tag is pushed
- [x] Remove Wercker and Travis if those are dropped

**Comment by jaapio** [comment]
Marked some tasks as done, we stick to travis for now. 
Releases of v3 are automated, when a tag is created a phar will be build and a new tag on docker hub will be created
